const products = [
  {
    _id: "1",
    name: "Chrome Tour",
    image: "/images/balls-2024-chrome-tour_2___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "2",
    name: "Chrome Tour Triple Track",
    image: "/images/balls-2024-chrome-tour-triple-track-b3g1_2___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "3",
    name: "Chrome Tour Triple Track 360",
    image: "/images/balls-2024-chrome-tour-360-triple-track_2___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "4",
    name: "Chrome Tour True Track",
    image: "/images/balls-2024-chrome-tour-trutrack_6224___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Chrome Tour Yellow",
    image: "/images/balls-2024-chrome-tour-yellow_1446___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Chrome Tour Triple Track Yellow",
    image: "/images/balls-2024-chrome-tour-triple-track-yellow_1446___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "7",
    name: "Chrome Tour Triple Track 360 Yellow",
    image: "/images/balls-2024-chrome-tour-360-triple-track_1446___2.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: "8",
    name: "Chrome Tour True Track Yellow",
    image: "/images/balls-2024-chrome-tour-trutrack-yellow_1446___2.webp",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: "Golf Proshop",
    category: "Golf",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
  },
];

export default products;
